### ISSUE TITLE
Call History page is slow when there are many calls

### ISSUE THREAD

**Issue by embbnux** [ringcentral/ringcentral-js-widgets#275]
if there are many call, it will be slow when user click call history tab
Maybe it need a pagination

**Comment by u9520107** [comment]
I suppose we can apply similar tactics as messages page.

**Comment by u9520107** [comment]
@embbnux I think we have planned a different call item implementation, consider implementing rendering only visible ones first, and render the rest later. Or some sort of simple pagination in UI layer.
Also, it turns out that the number factor in this slowness is the rendering of formatted numbers. We need to experiment with more enhancements to make this page behave faster... or at least make it feel faster.

BTW, read up on react performance tools if you haven't done so. It is quite helpful in finding out the bottleneck.

**Comment by tylerlong** [comment]
The current solution(workaround) is hacky:

```js
  componentDidMount() {
    this._mounted = true;
    setTimeout(() => {
      // clear timeout is probably not necessary
      if (this._mounted) {
        this.setState({
          loading: false,
        });
      }
    }, 10);
  }
```

More investigation is needed to find the root cause(for its slowness) and replace the workaround with a real solution.

**Comment by embbnux** [comment]
We can try https://github.com/seatgeek/react-infinite
